trigger:
 tags:
    include:
    - release-*

variables:
- group: Deployment

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x' # Use your desired Node.js version
    displayName: 'Set up Node.js'

  - script: |
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    displayName: 'Configure npm for Authentication'
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  - script: npm install
    displayName: 'Install dependencies'
  
  - script: npm run build
    displayName: 'Build the project'

  - script: npm publish
    displayName: 'Publish to npm'
    condition: contains(variables['Build.SourceBranch'], 'refs/tags/release')