const mockData = {
  'SU00302474': {
    partNumber: 'SU00302474',
    partDescription: 'CLAMP',
    localDescription: 'Неприменимо',
    group: 'F',
    pnc: '',
    pncLocalName: '',
    binCode: null,
    dimension1: 80,
    dimension2: 50,
    dimension3: 15,
    netWeight: 250,
    grossWeight: null,
    cubicMeasure: 600,
    hsCode: null,
    uzhsCode: null,
    origin: 'JP',
    supersededTo: ['1110109263', '137410PH00', '138010PH00', '139350PH00'],
    stockParts: [],
    prices: [
      {
        countryIntegrationID: 'TM',
        countryName: 'Turkmenistan ',
        regionIntegrationID: 'TK',
        regionName: 'Turkmenistan ',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$12.49',
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$22.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$21.49',
        },
      },
      {
        countryIntegrationID: 'TJ',
        countryName: 'Tajikistan',
        regionIntegrationID: 'TJ',
        regionName: 'Tajikistan',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: null,
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$23.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$22.49',
        },
      },
      {
        countryIntegrationID: 'UZ',
        countryName: 'Uzbekistan',
        regionIntegrationID: 'UZ',
        regionName: 'Uzbekistan',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$23.49',
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$42.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: null,
        },
      },
    ],
    deadStock: null,
  },
  '0400007660/1': {
    partNumber: '0400007660',
    partDescription: 'REPLACEMENT KIT,',
    localDescription: 'Неприменимо',
    group: 'J',
    pnc: '',
    pncLocalName: '',
    binCode: null,
    dimension1: 75,
    dimension2: 60,
    dimension3: 10,
    netWeight: 226,
    grossWeight: null,
    cubicMeasure: 450,
    hsCode: null,
    uzhsCode: null,
    origin: 'JP',
    supersededTo: ['1110109263', '137410PH00', '138010PH00', '139350PH00'],
    stockParts: [
      {
        quantityLookUpResult: 'Available',
        locationID: 'UZ-UZ-BS',
        locationName: 'Besten Stock',
      },
    ],
    prices: [
      {
        countryIntegrationID: 'TM',
        countryName: 'Turkmenistan ',
        regionIntegrationID: 'TK',
        regionName: 'Turkmenistan ',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$24.49',
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$25.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$23.49',
        },
      },
      {
        countryIntegrationID: 'TJ',
        countryName: 'Tajikistan',
        regionIntegrationID: 'TJ',
        regionName: 'Tajikistan',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$25.49',
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$26.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$22.49',
        },
      },
      {
        countryIntegrationID: 'UZ',
        countryName: 'Uzbekistan',
        regionIntegrationID: 'UZ',
        regionName: 'Uzbekistan',
        warrantyPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$26.49',
        },
        purchasePrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$21.49',
        },
        retailPrice: {
          value: 2.4875,
          currecntySymbol: '$',
          cultureName: 'en-US',
          formattedValue: '$21.49',
        },
      },
    ],
    deadStock: null,
    logId: 'd864e3b6-4b6b-4d22-be99-7d64063446eb',
  },
};
