/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LanguageKeys } from "./global/types/locale";
import { ErrorKeys } from "./global/lib/get-local-language";
import { PartInformation } from "./global/types/part-information";
import { DotNetObjectReference, MockJson } from "./global/types/components";
import { FormHook } from "./global/lib/form-hook";
import { InputParams } from "./global/types/general";
import { FormElementMapper, FormFieldParams, FormSelectFetcher, LocaleFormKeys, StructureObject } from "./global/types/forms";
import { InformationTableColumn } from "./components/components/information-table";
import { ActiveElement } from "./components/part-lookup/part-lookup";
import { AccordionItem } from "./components/components/shift-accordion";
import { ClaimPayload, ServiceItem, ServiceItemGroup, VehicleInformation } from "./global/types/vehicle-information";
import { ClaimFormType } from "./locales/vehicleLookup/claimableItems/type";
import { ActiveElement as ActiveElement1 } from "./components/vehicle-lookup/vehicle-lookup";
export { LanguageKeys } from "./global/types/locale";
export { ErrorKeys } from "./global/lib/get-local-language";
export { PartInformation } from "./global/types/part-information";
export { DotNetObjectReference, MockJson } from "./global/types/components";
export { FormHook } from "./global/lib/form-hook";
export { InputParams } from "./global/types/general";
export { FormElementMapper, FormFieldParams, FormSelectFetcher, LocaleFormKeys, StructureObject } from "./global/types/forms";
export { InformationTableColumn } from "./components/components/information-table";
export { ActiveElement } from "./components/part-lookup/part-lookup";
export { AccordionItem } from "./components/components/shift-accordion";
export { ClaimPayload, ServiceItem, ServiceItemGroup, VehicleInformation } from "./global/types/vehicle-information";
export { ClaimFormType } from "./locales/vehicleLookup/claimableItems/type";
export { ActiveElement as ActiveElement1 } from "./components/vehicle-lookup/vehicle-lookup";
export namespace Components {
    interface ContactUsForm {
        "baseUrl": string;
        "brandId": string;
        "errorCallback": (error: any) => void;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadingChanges": (loading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        /**
          * @default '6Lehq6IpAAAAAETTDS2Zh60nHIT1a8oVkRtJ2WsA'
         */
        "recaptchaKey": string;
        /**
          * @default '["submit.Submit"]'
         */
        "structure": string;
        "successCallback": (values: any) => void;
        "theme": string;
    }
    interface DeadStockLookup {
        /**
          * @default ''
         */
        "baseUrl": string;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (partNumber?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: PartInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<PartInformation>) => Promise<void>;
    }
    interface DistributorLookup {
        /**
          * @default ''
         */
        "baseUrl": string;
        "errorCallback": (errorMessage: string) => void;
        "fetchData": (partNumber?: string, headers?: any) => Promise<void>;
        /**
          * @default ''
         */
        "hiddenFields"?: string;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "localizationName"?: string;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: PartInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<PartInformation>) => Promise<void>;
    }
    interface FlexibleContainer {
        "addChildrenAnimation": (child: FlexibleContainer) => Promise<void>;
        "alwaysStrict"?: boolean;
        "classes"?: string;
        "containerClasses"?: string;
        /**
          * @default 'auto'
         */
        "height"?: number | 'auto';
        /**
          * @default true
         */
        "isOpened"?: boolean;
        "removeChildrenAnimation": (child: FlexibleContainer) => Promise<void>;
        /**
          * @default false
         */
        "stopAnimation"?: boolean;
        "subscribeAsParent": (parent: FlexibleContainer) => Promise<void>;
    }
    interface FormDialog {
        "dialogClosed": () => void;
        "errorMessage": string;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
    }
    interface FormInput {
        "class": string;
        "errorMessage": string;
        "form": FormHook<any>;
        "formLocaleName": LocaleFormKeys;
        "inputParams": InputParams;
        "inputPreFix": string;
        "isError": boolean;
        "isRequired": boolean;
        "label": string;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "numberDirection"?: boolean;
        "wrapperClass": string;
        "wrapperId": string;
    }
    interface FormSelect {
        "disabled": boolean;
        "errorMessage": string;
        "fetcher": FormSelectFetcher;
        "form": FormHook<any>;
        "formLocaleName": LocaleFormKeys;
        "isError": boolean;
        "isRequired": boolean;
        "label": string;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "name": string;
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        "wrapperClass": string;
        "wrapperId": string;
    }
    interface FormShadowInput {
        "form": FormHook<any>;
        "name": string;
        "value": string;
    }
    interface FormStructure {
        "errorMessage": string;
        "form": FormHook<any>;
        "formElementMapper": FormElementMapper<any>;
        "isLoading": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        /**
          * @default {}
         */
        "renderControl": {};
        /**
          * @default '["submit.Submit"]'
         */
        "structure": string;
        "theme": string;
        /**
          * @default {}
         */
        "themes": any;
    }
    interface FormStructureError {
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
    }
    interface FormSubmit {
        "isLoading": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        /**
          * @default {}
         */
        "params": FormFieldParams;
        "structureElement": StructureObject;
    }
    interface FormTextArea {
        "errorMessage": string;
        "form": FormHook<any>;
        "formLocaleName": LocaleFormKeys;
        "inputParams": InputParams;
        "isError": boolean;
        "isRequired": boolean;
        "label": string;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "wrapperClass": string;
        "wrapperId": string;
    }
    interface InformationTable {
        "headers": InformationTableColumn[];
        /**
          * @default false
         */
        "isLoading": boolean;
        /**
          * @default []
         */
        "rows": object[];
        /**
          * @default {}
         */
        "templateRow": object;
    }
    interface LoadingSpinner {
        "isLoading": boolean;
    }
    interface ManufacturerLookup {
        /**
          * @default ''
         */
        "baseUrl": string;
        "errorCallback": (errorMessage: string) => void;
        "fetchData": (partNumber?: string, headers?: any) => Promise<void>;
        /**
          * @default 'Manufacturer'
         */
        "headerTitle": string;
        /**
          * @default ''
         */
        "hiddenFields": string;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "localizationName"?: string;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: PartInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<PartInformation>) => Promise<void>;
    }
    interface PartLookup {
        /**
          * @default ''
         */
        "activeElement"?: ActiveElement;
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default ''
         */
        "blazorErrorStateListener": string;
        /**
          * @default ''
         */
        "blazorOnLoadingStateChange": string;
        "childrenProps"?: string | Object;
        "errorStateListener"?: (newError: string) => void;
        "fetchPartNumber": (partNumber: string, quantity?: string, headers?: any) => Promise<string>;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadingStateChanged"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setBlazorRef": (newBlazorRef: DotNetObjectReference) => Promise<void>;
    }
    interface ServiceBookingForm {
        "baseUrl": string;
        "brandId": string;
        "errorCallback": (error: any) => void;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadingChanges": (loading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        /**
          * @default '6Lehq6IpAAAAAETTDS2Zh60nHIT1a8oVkRtJ2WsA'
         */
        "recaptchaKey": string;
        /**
          * @default '["submit.Submit"]'
         */
        "structure": string;
        "successCallback": (values: any) => void;
        "theme": string;
    }
    interface ShiftAccordion {
        "accordionClasses"?: string;
        "accordionContentClasses"?: string;
        "items": AccordionItem[];
    }
    interface ShiftSlider {
        "activeIndex": number;
        "components": (() => Node)[];
    }
    interface ShiftTabContent {
        "activeComponent": string;
        "components": { [key: string]: Node };
    }
    interface ShiftTabs {
        "activeTabIndex": number;
        "activeTabLabel": string;
        "changeActiveTab": (activeStatus: { label: string; idx: number }) => void;
        "containerClasses"?: string;
        "tabClasses"?: string;
        "tabs": string[];
    }
    interface VehicleAccessories {
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default false
         */
        "coreOnly": boolean;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
    }
    interface VehicleClaimableItems {
        "activate"?: (vehicleInformation: VehicleInformation) => void;
        "baseUrl": string;
        "claim": (item: ServiceItem) => Promise<void>;
        /**
          * @default 'api/vehicle/swift-claim'
         */
        "claimEndPoint": string;
        "completeClaim": (response: any) => Promise<void>;
        /**
          * @default false
         */
        "coreOnly": boolean;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default {}
         */
        "headers": any;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default 30
         */
        "maximumDocumentFileSizeInMb": number;
        "print"?: (claimResponse: any) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
    }
    interface VehicleItemClaimForm {
        /**
          * @default null
         */
        "canceledItems"?: ServiceItem[];
        "getQrValue": () => Promise<string>;
        "handleClaiming"?: (payload: ClaimPayload) => void;
        /**
          * @default null
         */
        "item"?: ServiceItem;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default claimFormSchema.getDefault()
         */
        "locale": ClaimFormType;
        "maximumDocumentFileSizeInMb": number;
        "quite": () => Promise<void>;
        "setFileUploadProgression": (uploadPercentage: number) => Promise<void>;
        /**
          * @default null
         */
        "unInvoicedByBrokerName"?: string;
        /**
          * @default ''
         */
        "vin"?: string;
    }
    interface VehicleLookup {
        /**
          * @default ''
         */
        "activeElement"?: ActiveElement1;
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default ''
         */
        "blazorDynamicClaimActivate": string;
        /**
          * @default ''
         */
        "blazorErrorStateListener": string;
        /**
          * @default ''
         */
        "blazorOnLoadingStateChange": string;
        "childrenProps"?: string | Object;
        "dynamicClaimActivate"?: (vehicleInformation: VehicleInformation) => void;
        "errorStateListener"?: (newError: string) => void;
        "fetchVin": (vin: string, headers?: any) => Promise<string>;
        "handleLoadData": (newResponse: VehicleInformation, activeElement: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadingStateChanged"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setBlazorRef": (newBlazorRef: DotNetObjectReference) => Promise<void>;
    }
    interface VehiclePaintThickness {
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default false
         */
        "coreOnly": boolean;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
    }
    interface VehicleServiceHistory {
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default false
         */
        "coreOnly": boolean;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
    }
    interface VehicleSpecification {
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default false
         */
        "coreOnly": boolean;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
    }
    interface VehicleWarrantyDetails {
        /**
          * @default ''
         */
        "baseUrl": string;
        /**
          * @default null
         */
        "brandIntegrationId": string;
        /**
          * @default null
         */
        "cityId"?: string;
        /**
          * @default null
         */
        "cityIntegrationId"?: string;
        /**
          * @default null
         */
        "companyBranchId"?: string;
        /**
          * @default null
         */
        "companyBranchIntegrationId"?: string;
        /**
          * @default null
         */
        "companyId"?: string;
        /**
          * @default null
         */
        "companyIntegrationId"?: string;
        /**
          * @default false
         */
        "coreOnly": boolean;
        /**
          * @default null
         */
        "customerEmail"?: string;
        /**
          * @default null
         */
        "customerName"?: string;
        /**
          * @default null
         */
        "customerPhone"?: string;
        "errorCallback": (errorMessage: ErrorKeys) => void;
        "fetchData": (requestedVin?: string, headers?: any) => Promise<void>;
        /**
          * @default false
         */
        "isDev": boolean;
        /**
          * @default 'en'
         */
        "language": LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString": string;
        /**
          * @default ''
         */
        "recaptchaKey": string;
        "setData": (newData: VehicleInformation | string, headers?: any) => Promise<void>;
        "setErrorMessage": (message: ErrorKeys) => Promise<void>;
        "setMockData": (newMockData: MockJson<VehicleInformation>) => Promise<void>;
        /**
          * @default false
         */
        "showSsc": boolean;
        /**
          * @default false
         */
        "showWarranty": boolean;
        /**
          * @default ''
         */
        "unauthorizedSscLookupBaseUrl": string;
        /**
          * @default ''
         */
        "unauthorizedSscLookupQueryString": string;
        /**
          * @default null
         */
        "userId"?: string;
    }
    interface VinExtractor {
        /**
          * @default false
         */
        "captureEnvironment": boolean;
        /**
          * @default CAPTURE_INTERVAL
         */
        "captureInterval": number;
        "close": () => Promise<void>;
        /**
          * @default false
         */
        "manualCapture": boolean;
        "ocrEndpoint": string;
        "onError"?: ((newError: Error) => void) | string;
        "onExtract"?: ((vin: string) => void) | string;
        "onOpenChange"?: ((newError: boolean) => void) | string;
        "onProcessing"?: ((vin: string) => void) | string;
        "open": () => Promise<void>;
        /**
          * @default false
         */
        "readSticker": boolean;
        "setBlazorRef": (newBlazorRef: DotNetObjectReference) => Promise<void>;
        /**
          * @default false
         */
        "skipValidation": boolean;
        /**
          * @default ''
         */
        "title": string;
        "uploaderButtonId": string;
        /**
          * @default false
         */
        "useOcr": boolean;
        /**
          * @default false
         */
        "verbose": boolean;
    }
}
declare global {
    interface HTMLContactUsFormElement extends Components.ContactUsForm, HTMLStencilElement {
    }
    var HTMLContactUsFormElement: {
        prototype: HTMLContactUsFormElement;
        new (): HTMLContactUsFormElement;
    };
    interface HTMLDeadStockLookupElement extends Components.DeadStockLookup, HTMLStencilElement {
    }
    var HTMLDeadStockLookupElement: {
        prototype: HTMLDeadStockLookupElement;
        new (): HTMLDeadStockLookupElement;
    };
    interface HTMLDistributorLookupElement extends Components.DistributorLookup, HTMLStencilElement {
    }
    var HTMLDistributorLookupElement: {
        prototype: HTMLDistributorLookupElement;
        new (): HTMLDistributorLookupElement;
    };
    interface HTMLFlexibleContainerElement extends Components.FlexibleContainer, HTMLStencilElement {
    }
    var HTMLFlexibleContainerElement: {
        prototype: HTMLFlexibleContainerElement;
        new (): HTMLFlexibleContainerElement;
    };
    interface HTMLFormDialogElement extends Components.FormDialog, HTMLStencilElement {
    }
    var HTMLFormDialogElement: {
        prototype: HTMLFormDialogElement;
        new (): HTMLFormDialogElement;
    };
    interface HTMLFormInputElement extends Components.FormInput, HTMLStencilElement {
    }
    var HTMLFormInputElement: {
        prototype: HTMLFormInputElement;
        new (): HTMLFormInputElement;
    };
    interface HTMLFormSelectElement extends Components.FormSelect, HTMLStencilElement {
    }
    var HTMLFormSelectElement: {
        prototype: HTMLFormSelectElement;
        new (): HTMLFormSelectElement;
    };
    interface HTMLFormShadowInputElement extends Components.FormShadowInput, HTMLStencilElement {
    }
    var HTMLFormShadowInputElement: {
        prototype: HTMLFormShadowInputElement;
        new (): HTMLFormShadowInputElement;
    };
    interface HTMLFormStructureElement extends Components.FormStructure, HTMLStencilElement {
    }
    var HTMLFormStructureElement: {
        prototype: HTMLFormStructureElement;
        new (): HTMLFormStructureElement;
    };
    interface HTMLFormStructureErrorElement extends Components.FormStructureError, HTMLStencilElement {
    }
    var HTMLFormStructureErrorElement: {
        prototype: HTMLFormStructureErrorElement;
        new (): HTMLFormStructureErrorElement;
    };
    interface HTMLFormSubmitElement extends Components.FormSubmit, HTMLStencilElement {
    }
    var HTMLFormSubmitElement: {
        prototype: HTMLFormSubmitElement;
        new (): HTMLFormSubmitElement;
    };
    interface HTMLFormTextAreaElement extends Components.FormTextArea, HTMLStencilElement {
    }
    var HTMLFormTextAreaElement: {
        prototype: HTMLFormTextAreaElement;
        new (): HTMLFormTextAreaElement;
    };
    interface HTMLInformationTableElement extends Components.InformationTable, HTMLStencilElement {
    }
    var HTMLInformationTableElement: {
        prototype: HTMLInformationTableElement;
        new (): HTMLInformationTableElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLManufacturerLookupElement extends Components.ManufacturerLookup, HTMLStencilElement {
    }
    var HTMLManufacturerLookupElement: {
        prototype: HTMLManufacturerLookupElement;
        new (): HTMLManufacturerLookupElement;
    };
    interface HTMLPartLookupElement extends Components.PartLookup, HTMLStencilElement {
    }
    var HTMLPartLookupElement: {
        prototype: HTMLPartLookupElement;
        new (): HTMLPartLookupElement;
    };
    interface HTMLServiceBookingFormElement extends Components.ServiceBookingForm, HTMLStencilElement {
    }
    var HTMLServiceBookingFormElement: {
        prototype: HTMLServiceBookingFormElement;
        new (): HTMLServiceBookingFormElement;
    };
    interface HTMLShiftAccordionElement extends Components.ShiftAccordion, HTMLStencilElement {
    }
    var HTMLShiftAccordionElement: {
        prototype: HTMLShiftAccordionElement;
        new (): HTMLShiftAccordionElement;
    };
    interface HTMLShiftSliderElement extends Components.ShiftSlider, HTMLStencilElement {
    }
    var HTMLShiftSliderElement: {
        prototype: HTMLShiftSliderElement;
        new (): HTMLShiftSliderElement;
    };
    interface HTMLShiftTabContentElement extends Components.ShiftTabContent, HTMLStencilElement {
    }
    var HTMLShiftTabContentElement: {
        prototype: HTMLShiftTabContentElement;
        new (): HTMLShiftTabContentElement;
    };
    interface HTMLShiftTabsElement extends Components.ShiftTabs, HTMLStencilElement {
    }
    var HTMLShiftTabsElement: {
        prototype: HTMLShiftTabsElement;
        new (): HTMLShiftTabsElement;
    };
    interface HTMLVehicleAccessoriesElement extends Components.VehicleAccessories, HTMLStencilElement {
    }
    var HTMLVehicleAccessoriesElement: {
        prototype: HTMLVehicleAccessoriesElement;
        new (): HTMLVehicleAccessoriesElement;
    };
    interface HTMLVehicleClaimableItemsElement extends Components.VehicleClaimableItems, HTMLStencilElement {
    }
    var HTMLVehicleClaimableItemsElement: {
        prototype: HTMLVehicleClaimableItemsElement;
        new (): HTMLVehicleClaimableItemsElement;
    };
    interface HTMLVehicleItemClaimFormElement extends Components.VehicleItemClaimForm, HTMLStencilElement {
    }
    var HTMLVehicleItemClaimFormElement: {
        prototype: HTMLVehicleItemClaimFormElement;
        new (): HTMLVehicleItemClaimFormElement;
    };
    interface HTMLVehicleLookupElement extends Components.VehicleLookup, HTMLStencilElement {
    }
    var HTMLVehicleLookupElement: {
        prototype: HTMLVehicleLookupElement;
        new (): HTMLVehicleLookupElement;
    };
    interface HTMLVehiclePaintThicknessElement extends Components.VehiclePaintThickness, HTMLStencilElement {
    }
    var HTMLVehiclePaintThicknessElement: {
        prototype: HTMLVehiclePaintThicknessElement;
        new (): HTMLVehiclePaintThicknessElement;
    };
    interface HTMLVehicleServiceHistoryElement extends Components.VehicleServiceHistory, HTMLStencilElement {
    }
    var HTMLVehicleServiceHistoryElement: {
        prototype: HTMLVehicleServiceHistoryElement;
        new (): HTMLVehicleServiceHistoryElement;
    };
    interface HTMLVehicleSpecificationElement extends Components.VehicleSpecification, HTMLStencilElement {
    }
    var HTMLVehicleSpecificationElement: {
        prototype: HTMLVehicleSpecificationElement;
        new (): HTMLVehicleSpecificationElement;
    };
    interface HTMLVehicleWarrantyDetailsElement extends Components.VehicleWarrantyDetails, HTMLStencilElement {
    }
    var HTMLVehicleWarrantyDetailsElement: {
        prototype: HTMLVehicleWarrantyDetailsElement;
        new (): HTMLVehicleWarrantyDetailsElement;
    };
    interface HTMLVinExtractorElement extends Components.VinExtractor, HTMLStencilElement {
    }
    var HTMLVinExtractorElement: {
        prototype: HTMLVinExtractorElement;
        new (): HTMLVinExtractorElement;
    };
    interface HTMLElementTagNameMap {
        "contact-us-form": HTMLContactUsFormElement;
        "dead-stock-lookup": HTMLDeadStockLookupElement;
        "distributor-lookup": HTMLDistributorLookupElement;
        "flexible-container": HTMLFlexibleContainerElement;
        "form-dialog": HTMLFormDialogElement;
        "form-input": HTMLFormInputElement;
        "form-select": HTMLFormSelectElement;
        "form-shadow-input": HTMLFormShadowInputElement;
        "form-structure": HTMLFormStructureElement;
        "form-structure-error": HTMLFormStructureErrorElement;
        "form-submit": HTMLFormSubmitElement;
        "form-text-area": HTMLFormTextAreaElement;
        "information-table": HTMLInformationTableElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
        "manufacturer-lookup": HTMLManufacturerLookupElement;
        "part-lookup": HTMLPartLookupElement;
        "service-booking-form": HTMLServiceBookingFormElement;
        "shift-accordion": HTMLShiftAccordionElement;
        "shift-slider": HTMLShiftSliderElement;
        "shift-tab-content": HTMLShiftTabContentElement;
        "shift-tabs": HTMLShiftTabsElement;
        "vehicle-accessories": HTMLVehicleAccessoriesElement;
        "vehicle-claimable-items": HTMLVehicleClaimableItemsElement;
        "vehicle-item-claim-form": HTMLVehicleItemClaimFormElement;
        "vehicle-lookup": HTMLVehicleLookupElement;
        "vehicle-paint-thickness": HTMLVehiclePaintThicknessElement;
        "vehicle-service-history": HTMLVehicleServiceHistoryElement;
        "vehicle-specification": HTMLVehicleSpecificationElement;
        "vehicle-warranty-details": HTMLVehicleWarrantyDetailsElement;
        "vin-extractor": HTMLVinExtractorElement;
    }
}
declare namespace LocalJSX {
    interface ContactUsForm {
        "baseUrl"?: string;
        "brandId"?: string;
        "errorCallback"?: (error: any) => void;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadingChanges"?: (loading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
        /**
          * @default '6Lehq6IpAAAAAETTDS2Zh60nHIT1a8oVkRtJ2WsA'
         */
        "recaptchaKey"?: string;
        /**
          * @default '["submit.Submit"]'
         */
        "structure"?: string;
        "successCallback"?: (values: any) => void;
        "theme"?: string;
    }
    interface DeadStockLookup {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface DistributorLookup {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        "errorCallback"?: (errorMessage: string) => void;
        /**
          * @default ''
         */
        "hiddenFields"?: string;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "localizationName"?: string;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface FlexibleContainer {
        "alwaysStrict"?: boolean;
        "classes"?: string;
        "containerClasses"?: string;
        /**
          * @default 'auto'
         */
        "height"?: number | 'auto';
        /**
          * @default true
         */
        "isOpened"?: boolean;
        /**
          * @default false
         */
        "stopAnimation"?: boolean;
    }
    interface FormDialog {
        "dialogClosed"?: () => void;
        "errorMessage"?: string;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
    }
    interface FormInput {
        "class"?: string;
        "errorMessage"?: string;
        "form"?: FormHook<any>;
        "formLocaleName"?: LocaleFormKeys;
        "inputParams"?: InputParams;
        "inputPreFix"?: string;
        "isError"?: boolean;
        "isRequired"?: boolean;
        "label"?: string;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "numberDirection"?: boolean;
        "wrapperClass"?: string;
        "wrapperId"?: string;
    }
    interface FormSelect {
        "disabled"?: boolean;
        "errorMessage"?: string;
        "fetcher"?: FormSelectFetcher;
        "form"?: FormHook<any>;
        "formLocaleName"?: LocaleFormKeys;
        "isError"?: boolean;
        "isRequired"?: boolean;
        "label"?: string;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "name"?: string;
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        "wrapperClass"?: string;
        "wrapperId"?: string;
    }
    interface FormShadowInput {
        "form"?: FormHook<any>;
        "name"?: string;
        "value"?: string;
    }
    interface FormStructure {
        "errorMessage"?: string;
        "form"?: FormHook<any>;
        "formElementMapper"?: FormElementMapper<any>;
        "isLoading"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        /**
          * @default {}
         */
        "renderControl"?: {};
        /**
          * @default '["submit.Submit"]'
         */
        "structure"?: string;
        "theme"?: string;
        /**
          * @default {}
         */
        "themes"?: any;
    }
    interface FormStructureError {
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
    }
    interface FormSubmit {
        "isLoading"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        /**
          * @default {}
         */
        "params"?: FormFieldParams;
        "structureElement"?: StructureObject;
    }
    interface FormTextArea {
        "errorMessage"?: string;
        "form"?: FormHook<any>;
        "formLocaleName"?: LocaleFormKeys;
        "inputParams"?: InputParams;
        "isError"?: boolean;
        "isRequired"?: boolean;
        "label"?: string;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "wrapperClass"?: string;
        "wrapperId"?: string;
    }
    interface InformationTable {
        "headers"?: InformationTableColumn[];
        /**
          * @default false
         */
        "isLoading"?: boolean;
        /**
          * @default []
         */
        "rows"?: object[];
        /**
          * @default {}
         */
        "templateRow"?: object;
    }
    interface LoadingSpinner {
        "isLoading"?: boolean;
    }
    interface ManufacturerLookup {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        "errorCallback"?: (errorMessage: string) => void;
        /**
          * @default 'Manufacturer'
         */
        "headerTitle"?: string;
        /**
          * @default ''
         */
        "hiddenFields"?: string;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: PartInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "localizationName"?: string;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface PartLookup {
        /**
          * @default ''
         */
        "activeElement"?: ActiveElement;
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default ''
         */
        "blazorErrorStateListener"?: string;
        /**
          * @default ''
         */
        "blazorOnLoadingStateChange"?: string;
        "childrenProps"?: string | Object;
        "errorStateListener"?: (newError: string) => void;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadingStateChanged"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface ServiceBookingForm {
        "baseUrl"?: string;
        "brandId"?: string;
        "errorCallback"?: (error: any) => void;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadingChanges"?: (loading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
        /**
          * @default '6Lehq6IpAAAAAETTDS2Zh60nHIT1a8oVkRtJ2WsA'
         */
        "recaptchaKey"?: string;
        /**
          * @default '["submit.Submit"]'
         */
        "structure"?: string;
        "successCallback"?: (values: any) => void;
        "theme"?: string;
    }
    interface ShiftAccordion {
        "accordionClasses"?: string;
        "accordionContentClasses"?: string;
        "items"?: AccordionItem[];
    }
    interface ShiftSlider {
        "activeIndex"?: number;
        "components"?: (() => Node)[];
    }
    interface ShiftTabContent {
        "activeComponent"?: string;
        "components"?: { [key: string]: Node };
    }
    interface ShiftTabs {
        "activeTabIndex"?: number;
        "activeTabLabel"?: string;
        "changeActiveTab"?: (activeStatus: { label: string; idx: number }) => void;
        "containerClasses"?: string;
        "tabClasses"?: string;
        "tabs"?: string[];
    }
    interface VehicleAccessories {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehicleClaimableItems {
        "activate"?: (vehicleInformation: VehicleInformation) => void;
        "baseUrl"?: string;
        /**
          * @default 'api/vehicle/swift-claim'
         */
        "claimEndPoint"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default {}
         */
        "headers"?: any;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default 30
         */
        "maximumDocumentFileSizeInMb"?: number;
        "print"?: (claimResponse: any) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehicleItemClaimForm {
        /**
          * @default null
         */
        "canceledItems"?: ServiceItem[];
        "handleClaiming"?: (payload: ClaimPayload) => void;
        /**
          * @default null
         */
        "item"?: ServiceItem;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default claimFormSchema.getDefault()
         */
        "locale"?: ClaimFormType;
        "maximumDocumentFileSizeInMb"?: number;
        /**
          * @default null
         */
        "unInvoicedByBrokerName"?: string;
        /**
          * @default ''
         */
        "vin"?: string;
    }
    interface VehicleLookup {
        /**
          * @default ''
         */
        "activeElement"?: ActiveElement1;
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default ''
         */
        "blazorDynamicClaimActivate"?: string;
        /**
          * @default ''
         */
        "blazorErrorStateListener"?: string;
        /**
          * @default ''
         */
        "blazorOnLoadingStateChange"?: string;
        "childrenProps"?: string | Object;
        "dynamicClaimActivate"?: (vehicleInformation: VehicleInformation) => void;
        "errorStateListener"?: (newError: string) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadingStateChanged"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehiclePaintThickness {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehicleServiceHistory {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehicleSpecification {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
    }
    interface VehicleWarrantyDetails {
        /**
          * @default ''
         */
        "baseUrl"?: string;
        /**
          * @default null
         */
        "brandIntegrationId"?: string;
        /**
          * @default null
         */
        "cityId"?: string;
        /**
          * @default null
         */
        "cityIntegrationId"?: string;
        /**
          * @default null
         */
        "companyBranchId"?: string;
        /**
          * @default null
         */
        "companyBranchIntegrationId"?: string;
        /**
          * @default null
         */
        "companyId"?: string;
        /**
          * @default null
         */
        "companyIntegrationId"?: string;
        /**
          * @default false
         */
        "coreOnly"?: boolean;
        /**
          * @default null
         */
        "customerEmail"?: string;
        /**
          * @default null
         */
        "customerName"?: string;
        /**
          * @default null
         */
        "customerPhone"?: string;
        "errorCallback"?: (errorMessage: ErrorKeys) => void;
        /**
          * @default false
         */
        "isDev"?: boolean;
        /**
          * @default 'en'
         */
        "language"?: LanguageKeys;
        "loadedResponse"?: (response: VehicleInformation) => void;
        "loadingStateChange"?: (isLoading: boolean) => void;
        /**
          * @default ''
         */
        "queryString"?: string;
        /**
          * @default ''
         */
        "recaptchaKey"?: string;
        /**
          * @default false
         */
        "showSsc"?: boolean;
        /**
          * @default false
         */
        "showWarranty"?: boolean;
        /**
          * @default ''
         */
        "unauthorizedSscLookupBaseUrl"?: string;
        /**
          * @default ''
         */
        "unauthorizedSscLookupQueryString"?: string;
        /**
          * @default null
         */
        "userId"?: string;
    }
    interface VinExtractor {
        /**
          * @default false
         */
        "captureEnvironment"?: boolean;
        /**
          * @default CAPTURE_INTERVAL
         */
        "captureInterval"?: number;
        /**
          * @default false
         */
        "manualCapture"?: boolean;
        "ocrEndpoint"?: string;
        "onError"?: ((newError: Error) => void) | string;
        "onExtract"?: ((vin: string) => void) | string;
        "onOpenChange"?: ((newError: boolean) => void) | string;
        "onProcessing"?: ((vin: string) => void) | string;
        /**
          * @default false
         */
        "readSticker"?: boolean;
        /**
          * @default false
         */
        "skipValidation"?: boolean;
        /**
          * @default ''
         */
        "title"?: string;
        "uploaderButtonId"?: string;
        /**
          * @default false
         */
        "useOcr"?: boolean;
        /**
          * @default false
         */
        "verbose"?: boolean;
    }
    interface IntrinsicElements {
        "contact-us-form": ContactUsForm;
        "dead-stock-lookup": DeadStockLookup;
        "distributor-lookup": DistributorLookup;
        "flexible-container": FlexibleContainer;
        "form-dialog": FormDialog;
        "form-input": FormInput;
        "form-select": FormSelect;
        "form-shadow-input": FormShadowInput;
        "form-structure": FormStructure;
        "form-structure-error": FormStructureError;
        "form-submit": FormSubmit;
        "form-text-area": FormTextArea;
        "information-table": InformationTable;
        "loading-spinner": LoadingSpinner;
        "manufacturer-lookup": ManufacturerLookup;
        "part-lookup": PartLookup;
        "service-booking-form": ServiceBookingForm;
        "shift-accordion": ShiftAccordion;
        "shift-slider": ShiftSlider;
        "shift-tab-content": ShiftTabContent;
        "shift-tabs": ShiftTabs;
        "vehicle-accessories": VehicleAccessories;
        "vehicle-claimable-items": VehicleClaimableItems;
        "vehicle-item-claim-form": VehicleItemClaimForm;
        "vehicle-lookup": VehicleLookup;
        "vehicle-paint-thickness": VehiclePaintThickness;
        "vehicle-service-history": VehicleServiceHistory;
        "vehicle-specification": VehicleSpecification;
        "vehicle-warranty-details": VehicleWarrantyDetails;
        "vin-extractor": VinExtractor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "contact-us-form": LocalJSX.ContactUsForm & JSXBase.HTMLAttributes<HTMLContactUsFormElement>;
            "dead-stock-lookup": LocalJSX.DeadStockLookup & JSXBase.HTMLAttributes<HTMLDeadStockLookupElement>;
            "distributor-lookup": LocalJSX.DistributorLookup & JSXBase.HTMLAttributes<HTMLDistributorLookupElement>;
            "flexible-container": LocalJSX.FlexibleContainer & JSXBase.HTMLAttributes<HTMLFlexibleContainerElement>;
            "form-dialog": LocalJSX.FormDialog & JSXBase.HTMLAttributes<HTMLFormDialogElement>;
            "form-input": LocalJSX.FormInput & JSXBase.HTMLAttributes<HTMLFormInputElement>;
            "form-select": LocalJSX.FormSelect & JSXBase.HTMLAttributes<HTMLFormSelectElement>;
            "form-shadow-input": LocalJSX.FormShadowInput & JSXBase.HTMLAttributes<HTMLFormShadowInputElement>;
            "form-structure": LocalJSX.FormStructure & JSXBase.HTMLAttributes<HTMLFormStructureElement>;
            "form-structure-error": LocalJSX.FormStructureError & JSXBase.HTMLAttributes<HTMLFormStructureErrorElement>;
            "form-submit": LocalJSX.FormSubmit & JSXBase.HTMLAttributes<HTMLFormSubmitElement>;
            "form-text-area": LocalJSX.FormTextArea & JSXBase.HTMLAttributes<HTMLFormTextAreaElement>;
            "information-table": LocalJSX.InformationTable & JSXBase.HTMLAttributes<HTMLInformationTableElement>;
            "loading-spinner": LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "manufacturer-lookup": LocalJSX.ManufacturerLookup & JSXBase.HTMLAttributes<HTMLManufacturerLookupElement>;
            "part-lookup": LocalJSX.PartLookup & JSXBase.HTMLAttributes<HTMLPartLookupElement>;
            "service-booking-form": LocalJSX.ServiceBookingForm & JSXBase.HTMLAttributes<HTMLServiceBookingFormElement>;
            "shift-accordion": LocalJSX.ShiftAccordion & JSXBase.HTMLAttributes<HTMLShiftAccordionElement>;
            "shift-slider": LocalJSX.ShiftSlider & JSXBase.HTMLAttributes<HTMLShiftSliderElement>;
            "shift-tab-content": LocalJSX.ShiftTabContent & JSXBase.HTMLAttributes<HTMLShiftTabContentElement>;
            "shift-tabs": LocalJSX.ShiftTabs & JSXBase.HTMLAttributes<HTMLShiftTabsElement>;
            "vehicle-accessories": LocalJSX.VehicleAccessories & JSXBase.HTMLAttributes<HTMLVehicleAccessoriesElement>;
            "vehicle-claimable-items": LocalJSX.VehicleClaimableItems & JSXBase.HTMLAttributes<HTMLVehicleClaimableItemsElement>;
            "vehicle-item-claim-form": LocalJSX.VehicleItemClaimForm & JSXBase.HTMLAttributes<HTMLVehicleItemClaimFormElement>;
            "vehicle-lookup": LocalJSX.VehicleLookup & JSXBase.HTMLAttributes<HTMLVehicleLookupElement>;
            "vehicle-paint-thickness": LocalJSX.VehiclePaintThickness & JSXBase.HTMLAttributes<HTMLVehiclePaintThicknessElement>;
            "vehicle-service-history": LocalJSX.VehicleServiceHistory & JSXBase.HTMLAttributes<HTMLVehicleServiceHistoryElement>;
            "vehicle-specification": LocalJSX.VehicleSpecification & JSXBase.HTMLAttributes<HTMLVehicleSpecificationElement>;
            "vehicle-warranty-details": LocalJSX.VehicleWarrantyDetails & JSXBase.HTMLAttributes<HTMLVehicleWarrantyDetailsElement>;
            "vin-extractor": LocalJSX.VinExtractor & JSXBase.HTMLAttributes<HTMLVinExtractorElement>;
        }
    }
}
