// This file is auto-generated. Do not edit it manually.
// Use command: yarn generate-locale-mapper// It is generated by the script located at: generate-locale-mapper.mjs

const localeMapper = {
  "-": [
    "locales/"
  ],
  "errors": [
    "locales/errors/"
  ],
  "forms": [
    "locales/forms/",
    "locales/forms/contactUs/"
  ],
  "forms.contactUs": [
    "locales/forms/contactUs/"
  ],
  "general": [
    "locales/general/"
  ],
  "generalTicketTypes": [
    "locales/generalTicketTypes/"
  ],
  "partLookup.deadStock": [
    "locales/partLookup/deadStock/"
  ],
  "partLookup": [
    "locales/partLookup/deadStock/",
    "locales/partLookup/distributor/",
    "locales/partLookup/manufacturer/"
  ],
  "partLookup.distributor": [
    "locales/partLookup/distributor/"
  ],
  "partLookup.manufacturer": [
    "locales/partLookup/manufacturer/"
  ],
  "vehicleLookup.accessories": [
    "locales/vehicleLookup/accessories/"
  ],
  "vehicleLookup": [
    "locales/vehicleLookup/accessories/",
    "locales/vehicleLookup/dynamicClaim/",
    "locales/vehicleLookup/dynamicRedeem/",
    "locales/vehicleLookup/paintThickness/",
    "locales/vehicleLookup/serviceHistory/",
    "locales/vehicleLookup/specification/",
    "locales/vehicleLookup/warranty/"
  ],
  "vehicleLookup.dynamicClaim": [
    "locales/vehicleLookup/dynamicClaim/"
  ],
  "vehicleLookup.dynamicRedeem": [
    "locales/vehicleLookup/dynamicRedeem/"
  ],
  "vehicleLookup.paintThickness": [
    "locales/vehicleLookup/paintThickness/"
  ],
  "vehicleLookup.serviceHistory": [
    "locales/vehicleLookup/serviceHistory/"
  ],
  "vehicleLookup.specification": [
    "locales/vehicleLookup/specification/"
  ],
  "vehicleLookup.warranty": [
    "locales/vehicleLookup/warranty/"
  ]
} as const;

export default localeMapper;
