site_name: ADP - Components

use_directory_urls: false

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - navigation.collapse
    - header.autohide

extra_css:
  - extra/css/extra.css

extra_javascript:
  - extra/js/script.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Theming: theming.md
  - Components:
      - components/components-list.md
      - Vehicle Lookup Wrapper: components/vehicle-lookup.md
      - Vehicle Specification: components/vehicle-specification.md
      - Vehicle Accessories: components/vehicle-accessories.md
      - Warranty Details: components/warranty-details.md
      - Service History: components/service-history.md
      - Paint Thickness: components/paint-thickness.md
      - Swift Claim: components/swift-claim.md
      - Dead Stock Lookup: components/dead-stock-lookup.md
      - Distributor Lookup: components/distributor-lookup.md
      - Manufacturer Lookup: components/manufacturer-lookup.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.mark
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
